name: backdrp_fm
description: "BACKDRP.FM — DJ set catalog"
publish_to: 'none' # keep private

version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'   # matches your Dart version

dependencies:
  flutter:
    sdk: flutter

  # State management
  flutter_bloc: ^9.0.0
  equatable: ^2.0.7

  # Routing
  go_router: ^14.2.0

  # Firebase
  firebase_core: ^2.27.0
  firebase_auth: ^4.19.0
  cloud_firestore: ^4.15.0
  firebase_storage: ^11.7.0
  firebase_messaging: ^14.9.0
  firebase_analytics: ^10.10.0
  firebase_app_check: ^0.2.0+1

  # Audio
  just_audio: ^0.9.39
  audio_session: ^0.1.21

  # Utils
  url_launcher: ^6.3.0
  intl: ^0.19.0

  # iOS style icons
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.4.11
  freezed: ^2.5.7
  freezed_annotation: ^2.4.4
  json_serializable: ^6.9.3
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
