name: CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  flutter-ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          # If you want to pin to a specific version, uncomment the next line:
          # flutter-version: '3.19.6'

      - name: Flutter pub get
        run: flutter pub get

      - name: Analyze
        run: flutter analyze

      - name: Test
        run: flutter test --no-pub
