name: Build & Deploy to Firebase Hosting

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Flutter (stable)
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          # Optionally pin to your local version:
          # flutter-version: '3.19.6'

      - name: Install dependencies
        run: flutter pub get

      - name: Build Web (release)
        run: flutter build web --release

      - name: Deploy to Firebase (Hosting + Rules)
        uses: w9jds/firebase-action@v13.29.0
        with:
          args: deploy --only hosting,firestore:rules,storage
        env:
          GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}
          PROJECT_ID: ${{ secrets.PROJECT_ID }}
