name: Preview Channel Deploy

on:
  pull_request:
    branches: [ main ]

jobs:
  preview:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: stable
      - run: flutter pub get
      - run: flutter build web --release
      - name: Deploy Preview
        uses: w9jds/firebase-action@v13.29.0
        with:
          args: hosting:channel:deploy pr-${{ github.event.number }} --expires 7d
        env:
          GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}
          PROJECT_ID: ${{ secrets.PROJECT_ID }}
